### ISSUE TITLE
Improve the site navigation

### ISSUE THREAD

**Issue by deemp** [KovalevDima/ClickHaskell#73]
Currently, the site has a tree-like structure and doesn't let a visitor to quickly go to any site page.

I believe it'd be nice if the site had a sidebar with a ToC like the one in the [Nix manual](https://nix.dev/manual/nix/2.25/command-ref/nix-store.html?searchbar=) (they use mdBook) so that related pages can be grouped and it's possible to go to any site page.

**Comment by KovalevDima** [comment]
I've been thinking about this too. The QA/ directory structure was designed for ToC based on file paths
Currently it's following next pattern:
```
├-README.md
├-subdir/
| ├-README.md (or README.lhs)
| ├-nonREADME*.md (or nonREADME*.lhs)
| └-...
├-...
...
```
This directory integrated into hakyll compiler which generated static site files via `pandoc`
(see `QA/documentation-compiler/documentation-compiler.hs`)

Hakyll allows to set file paths by user defined rules. I defined next two rules:
1. `README` files translates to `index.html`:
`path/to/README.md` (or .lhs) translates into `path/to/index.html` (which is accessed by `/path/to/` in browser)
2. Other than `README` translates directly:
`path/to/nonReadme.lhs` (or .lhs) translated into `path/to/nonReadme.html`

This rules was specially designed to implement navigation generator which is integrated with QA dir via file paths

You can run live server with documentation compiler in project root directory via cabal
```bash
cabal run documentation-compiler -- watch
```
or build it with via `cabal` or `nix`
```bash
nix build .#documentation   # used on CI/CD for deploy documentation
cabal run documentation-compiler -- build
```

**Comment by KovalevDima** [comment]
I implemented loading of navigation links into compiler. Now we need to pass them into template

**Comment by KovalevDima** [comment]
I implemented passing links into html template
@deemp can you review updated site navigation UX?

**Comment by deemp** [comment]
@KovalevDima, it's much better now as I can see all paths on the site!

![image](https://github.com/user-attachments/assets/805e8e11-ac6e-4539-983f-6cb04fe68a9c)


I can suggest some small improvements to the navigation.
- Replace paths with (sub)section names. E.g., `/testing/` -> `Testing`.
- Show menu items as a tree-like structure. E.g.:
  ```
  - Usage
    - insertInto
    - selectFromView
  ```

**Comment by KovalevDima** [comment]
I think it would be nice to implement styling for working with documentation navigation as\
directory tree navigation in text editors on actual docs files.

I believe it's nice for developers:
1. To see something very familiar while reading documentation
2. To navigate over actual file paths 

and this design decision will improve
1. documentation contribution retention a lot
2. library confidence

by forcing developers to learn actual files mapping in repository\
and making them feel that everything is familiar

## I see it as
```bash
# when we at "/"
/development/
/testing/
/usage/

# when we at "/usage/
/development/
/testing/
/usage/
 ├insertInto
 └selectFromView

```

What do you think about it? Can I merge PR (which will close this issue) and to open another one with proposed redesign?

**Comment by deemp** [comment]
> Can I merge PR (which will close this issue) and to open another one with proposed redesign?

@KovalevDima, yes, sure, you can merge the PR.
