### ISSUE TITLE
[Question] What is the recommended way to do an aggregation with parameters?

### ISSUE THREAD

**Issue by BurningLutz** [KovalevDima/ClickHaskell#75]
First, I want to say thanks for your efforts on this library! :+1::+1:
(I had to do querys with clickhouse client, making it output csv, and then process that csv in haskell before.)

My question is that, with `select` function, I can do an aggregation like:
```sql
SELECT count(*), toDate(time) AS date FROM events GROUP BY date
```
But I want an aggregation with filtering:
```sql
SELECT count(*), toDate(time) AS date FROM events WHERE time >= ? and time < ? GROUP BY date
```
Such an aggregation needs some parameters to be passed. But `select` doesn't accept parameters.

What is the recommended way to do such an aggregation?

**Comment by KovalevDima** [comment]
Thanks for your feedback! 

Currently you can:
1. [Create a Parameterized View](https://clickhouse.com/docs/en/sql-reference/statements/create/view#parameterized-view) which takes this parameters and pass them using [selectFromView](https://kovalevdima.github.io/ClickHaskell/usage/selectFromView.html).
    ```sql
    CREATE VIEW eventsByPeriod
    SELECT count(*), toDate(time) AS date
    FROM events
    WHERE time >= {from:DateTime} and time < {to:DateTime}
    GROUP BY date
    ```
    I prefer this method since it allows you to switch implementation "on the fly" (via [CREATE OR REPLACE VIEW](https://clickhouse.com/docs/en/sql-reference/statements/create/view#normal-view))\
    which might be useful during migrations and quick queries fixes directly in database CI/CD pipeline.
2. Use query serialization of ClickHouse types directly via ToQueryPart(..) class like:
    ```haskell
    example :: ChDateTime -> ChDateTime -> Builder
    example startTime endTime
      = "SELECT count(*), toDate(time) AS date"
      <> "FROM events"
      <> "WHERE time >=" <> toQueryPart startTime  <> "and time <" <> toQueryPart endTime
      <> "GROUP BY date"
    ```


# About parameters passing design in general 
`selectFromView` works via query serialization under the hood as follows
```haskell
  let query =
        "SELECT " <> readingColumns @view @record <>
        " FROM " <> (byteString . BS8.pack . symbolVal @name) Proxy <> parameters interpreter
                 {- ^ tableName -}                                  {- ^ renderedParameters -}
```
![image](https://github.com/user-attachments/assets/737af119-d213-4ce2-8cc0-44fa744b8933)
each parameter serialization done via `toQueryPart` (which is tested via [T1QuerySerialization test](https://github.com/KovalevDima/ClickHaskell/blob/master/QA/testing/T1QuerySerialization.hs))

## Options to support
It's might be possible to implement passing parameters to queries using Native protocol\
starting from ClickHouse revision `DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS`
```haskell
data QueryPacket = MkQueryPacket
  { ...
  , parameters :: QueryParameters `SinceRevision` DBMS_MIN_PROTOCOL_VERSION_WITH_PARAMETERS
  }
  deriving (Generic, Serializable)
  ```
by execution parameterised query as follows
```sql
SELECT count(*), toDate(time) AS date
FROM events
WHERE time >= {from:DateTime} and time < {to:DateTime}
GROUP BY date
```

**Comment by BurningLutz** [comment]
Hi @KovalevDima, many thanks for your detailed illustration! I think I'll take the second approach as a starting point, and keep exploring this library. 😄
