### ISSUE TITLE
Implement query serialization for UUID ClickHouse type

### ISSUE THREAD

**Issue by KovalevDima** [KovalevDima/ClickHaskell#77]
To close this issue you need to uncomment test
```haskell
t1 :: Connection -> IO ()
t1 conn = do
  ...
  -- ToDo: runTestForType @ChUUID conn [minBound, toEnum 0, maxBound]
```
which causes compilation error
```
No instance for ‘ToQueryPart ChUUID’
```
and implement
```haskell
instance ToQueryPart ChUUID where
  toQueryPart (MkChUUID w128) =  undefined
```
which passes the Test1

You can take [uuid-types](https://hackage.haskell.org/package/uuid-types-1.0.6/docs/src/Data.UUID.Types.Internal.html#toString) implementation as a reference

**Comment by lambdajon** [comment]
If this task is actual, I would like to do it.

**Comment by KovalevDima** [comment]
Hi @lambdajon!
Every issue is relevant, so feel free to open a PR!
Also feel free to suggest any improvements to the documentation or project structure
I see in your repository that you are familiar with Nix, so I think you can start with [testing](https://kovalevdima.github.io/ClickHaskell/testing/) documentation

**Comment by lambdajon** [comment]
Hi @lambdajon!
Okay, I'll try to help with this too!
I'd also like to contribute to your repository for practice in Haskell, if you have any tasks for beginners, please post them in the issues!
Thanks for answer!

**Comment by KovalevDima** [comment]
My personal goal is to create friendly contribution environment. I always add  `good first issue` to issues I find suitable for newcomers in Nix/Haskell/ClickHouse. I'll put more effort to create issues, especially for newcomers.

Thank you for your interest! Feel free to ask for any help and please leave as much feedback about your experience as your can. I was working with this project a long time and there are might be a lot of opinionated decisions and missing information. Any conversation will help you to learn project too.
