### ISSUE TITLE
Timeout hardcoded

### ISSUE THREAD

**Issue by lambdajon** [KovalevDima/ClickHaskell#88]
If I understand correctly, the connection timeout should be taken from the config and should be in defaultCredentials.
[Reference](https://github.com/KovalevDima/ClickHaskell/blob/7d21a3cd221477c4fa52c2da21db87ac683269a3/distribution/ClickHaskell.hs#L113)

### Possible Solution.

```haskell
=<< timeout chConnetionTImeout
```

**Comment by KovalevDima** [comment]
It's not a socket TTL or DBMS response waiting timeout. It's a TCP socket opening timeout which is OS level syscall
As far as I can understand this operation should be handled much more faster than 3 seconds and It's a common practice to hardcode this value in TCP protocol. After connection established there is no more timeouts
You can find an example in Haskell library `network-simple` [connectSock](https://hackage.haskell.org/package/network-simple-0.4.5/docs/src/Network.Simple.TCP.html#connectSock) function, which I was using as a reference

If there are any considerations about it in RFCs to provide control, increase or delete this timeout than leave me a link please

**Comment by lambdajon** [comment]
@KovalevDima I understand you and will use your idea! Thanks for the answer!
